//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOTlazyZone.ViewResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NOTlazyZone.ViewResources.GlobalResources", typeof(GlobalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string Adres {
            get {
                return ResourceManager.GetString("Adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DaneKontaktowe.
        /// </summary>
        public static string DaneKontaktowe {
            get {
                return ResourceManager.GetString("DaneKontaktowe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataUrodzenia.
        /// </summary>
        public static string DataUrodzenia {
            get {
                return ResourceManager.GetString("DataUrodzenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DodatkoweKontrole.
        /// </summary>
        public static string DodatkoweKontrole {
            get {
                return ResourceManager.GetString("DodatkoweKontrole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DodatkowePola.
        /// </summary>
        public static string DodatkowePola {
            get {
                return ResourceManager.GetString("DodatkowePola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imie.
        /// </summary>
        public static string Imie {
            get {
                return ResourceManager.GetString("Imie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImieINaziwsko.
        /// </summary>
        public static string ImieINazwisko {
            get {
                return ResourceManager.GetString("ImieINazwisko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InformacjeOTransakcji.
        /// </summary>
        public static string InformacjeOTransakcji {
            get {
                return ResourceManager.GetString("InformacjeOTransakcji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KodPodcztowy.
        /// </summary>
        public static string KodPocztowy {
            get {
                return ResourceManager.GetString("KodPocztowy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KwotaTransakcji.
        /// </summary>
        public static string KwotaTransakcji {
            get {
                return ResourceManager.GetString("KwotaTransakcji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        public static string Nazwa {
            get {
                return ResourceManager.GetString("Nazwa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko.
        /// </summary>
        public static string Nazwisko {
            get {
                return ResourceManager.GetString("Nazwisko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OstatniaTransakcja.
        /// </summary>
        public static string OstatniaTransakcja {
            get {
                return ResourceManager.GetString("OstatniaTransakcja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plec.
        /// </summary>
        public static string Plec {
            get {
                return ResourceManager.GetString("Plec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PodstawoweDane.
        /// </summary>
        public static string PodstawoweDane {
            get {
                return ResourceManager.GetString("PodstawoweDane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatusKlienta.
        /// </summary>
        public static string StatusKlienta {
            get {
                return ResourceManager.GetString("StatusKlienta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StronaWWW.
        /// </summary>
        public static string StronaWWW {
            get {
                return ResourceManager.GetString("StronaWWW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Telefon {
            get {
                return ResourceManager.GetString("Telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrenerAktywny.
        /// </summary>
        public static string TrenerAktywny {
            get {
                return ResourceManager.GetString("TrenerAktywny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiek.
        /// </summary>
        public static string Wiek {
            get {
                return ResourceManager.GetString("Wiek", resourceCulture);
            }
        }
    }
}
