//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOTlazyZone.ViewResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NOTlazyZone.ViewResources.SettingResources", typeof(SettingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas odpoczynku między seriami (0,5 min):.
        /// </summary>
        public static string CzasOdpoczynkuMiędzySeriami {
            get {
                return ResourceManager.GetString("CzasOdpoczynkuMiędzySeriami", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Częstotliwość powiadomień:.
        /// </summary>
        public static string czestotliwoscPowiadomien {
            get {
                return ResourceManager.GetString("czestotliwoscPowiadomien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Częstotliwość treningów (dni/tydzień).
        /// </summary>
        public static string CzestotliwoscTreningow {
            get {
                return ResourceManager.GetString("CzestotliwoscTreningow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieta.
        /// </summary>
        public static string Dieta {
            get {
                return ResourceManager.GetString("Dieta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodatkowe uwagi dotyczące diety.
        /// </summary>
        public static string dodatkoweUwagiDotyczaceDiety {
            get {
                return ResourceManager.GetString("dodatkoweUwagiDotyczaceDiety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dzienna kaloryczność  (kcal).
        /// </summary>
        public static string DziennaKalorycznosc {
            get {
                return ResourceManager.GetString("DziennaKalorycznosc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dzienne spożycie białka (gramy):.
        /// </summary>
        public static string dzienneSpozycieBialka {
            get {
                return ResourceManager.GetString("dzienneSpozycieBialka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Głośność przypomnień:.
        /// </summary>
        public static string glosnoscPrzypomnien {
            get {
                return ResourceManager.GetString("glosnoscPrzypomnien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godzina otrzymywania powiadomień:.
        /// </summary>
        public static string godzinaOtrzymywaniaPowiadomien {
            get {
                return ResourceManager.GetString("godzinaOtrzymywaniaPowiadomien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło:.
        /// </summary>
        public static string Hasło {
            get {
                return ResourceManager.GetString("Hasło", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intensywność ćwiczeń.
        /// </summary>
        public static string intensywnoscCwiczen_ {
            get {
                return ResourceManager.GetString("intensywnoscCwiczen ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Język:.
        /// </summary>
        public static string Jezyk {
            get {
                return ResourceManager.GetString("Jezyk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba powtórzeń na serię.
        /// </summary>
        public static string liczbaPowtórzeńNaSerię {
            get {
                return ResourceManager.GetString("liczbaPowtórzeńNaSerię", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to liczba serii .
        /// </summary>
        public static string liczbaSerii {
            get {
                return ResourceManager.GetString("liczbaSerii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa:.
        /// </summary>
        public static string Nazwa {
            get {
                return ResourceManager.GetString("Nazwa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otrzymuj aktualizacje postępów.
        /// </summary>
        public static string otrzymujAktualizacjePostepow {
            get {
                return ResourceManager.GetString("otrzymujAktualizacjePostepow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otrzymuj powiadomienia o aktualizacjach diet.
        /// </summary>
        public static string otrzymujPowiadomieniaOAktualizacjachDiet {
            get {
                return ResourceManager.GetString("otrzymujPowiadomieniaOAktualizacjachDiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otrzymuj powiadomienia o nowych ćwiczeniach.
        /// </summary>
        public static string otrzymujPowiadomieniaONowychCwiczeniach {
            get {
                return ResourceManager.GetString("otrzymujPowiadomieniaONowychCwiczeniach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otrzymuj powiadomienia o wydarzeniach.
        /// </summary>
        public static string otrzymujPowiadomieniaOWydarzeniach {
            get {
                return ResourceManager.GetString("otrzymujPowiadomieniaOWydarzeniach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otrzymuj przypomnienia o posiłkach.
        /// </summary>
        public static string otrzymujPrzypomnieniaOPosilkach {
            get {
                return ResourceManager.GetString("otrzymujPrzypomnieniaOPosilkach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otrzymuj przypomnienia o treningu.
        /// </summary>
        public static string otrzymujPrzypomnieniaOTreningu {
            get {
                return ResourceManager.GetString("otrzymujPrzypomnieniaOTreningu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posiłki na dzień:.
        /// </summary>
        public static string posilkiNaDzien {
            get {
                return ResourceManager.GetString("posilkiNaDzien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powiadomienia.
        /// </summary>
        public static string Powiadomienia {
            get {
                return ResourceManager.GetString("Powiadomienia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poziom intensywności kardio.
        /// </summary>
        public static string poziomIntensywnościKardio {
            get {
                return ResourceManager.GetString("poziomIntensywnościKardio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preferowane produkty spozywcze.
        /// </summary>
        public static string preferowaneProduktySpozywcze {
            get {
                return ResourceManager.GetString("preferowaneProduktySpozywcze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferowany czas trwania cardio (co 20 minut):.
        /// </summary>
        public static string preferowanyCzasTrwaniaCardio {
            get {
                return ResourceManager.GetString("preferowanyCzasTrwaniaCardio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferowany czas trwania treningu (co 30 minut):.
        /// </summary>
        public static string PreferowanyCzasTrwaniaTreningu {
            get {
                return ResourceManager.GetString("PreferowanyCzasTrwaniaTreningu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferowany rodzaj diety.
        /// </summary>
        public static string preferowanyRodzajDiety {
            get {
                return ResourceManager.GetString("preferowanyRodzajDiety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferowany rodzaj treningu:.
        /// </summary>
        public static string PreferowanyRodzajTreningu {
            get {
                return ResourceManager.GetString("PreferowanyRodzajTreningu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procent tkanki tłuszczowej:.
        /// </summary>
        public static string ProcentTkankiTłuszczowej {
            get {
                return ResourceManager.GetString("ProcentTkankiTłuszczowej", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string Profil {
            get {
                return ResourceManager.GetString("Profil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spożycie wody (litry):.
        /// </summary>
        public static string SpozycieWody {
            get {
                return ResourceManager.GetString("SpozycieWody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprzęt do treningu siłowego:.
        /// </summary>
        public static string sprzetDoTreninguSilowego {
            get {
                return ResourceManager.GetString("sprzetDoTreninguSilowego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to srodowiskoTreningowe:.
        /// </summary>
        public static string srodowiskoTreningowe {
            get {
                return ResourceManager.GetString("srodowiskoTreningowe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trening.
        /// </summary>
        public static string Trening {
            get {
                return ResourceManager.GetString("Trening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ustawienia Diety .
        /// </summary>
        public static string ustawieniaDiety {
            get {
                return ResourceManager.GetString("ustawieniaDiety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia Powiadomień.
        /// </summary>
        public static string ustawieniaPowiadomien {
            get {
                return ResourceManager.GetString("ustawieniaPowiadomien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia Profilu.
        /// </summary>
        public static string UstawieniaProfilu {
            get {
                return ResourceManager.GetString("UstawieniaProfilu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia Treningu.
        /// </summary>
        public static string UstawieniaTreningu {
            get {
                return ResourceManager.GetString("UstawieniaTreningu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waga (kg):.
        /// </summary>
        public static string waga {
            get {
                return ResourceManager.GetString("waga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wzrost (cm):.
        /// </summary>
        public static string wzrost {
            get {
                return ResourceManager.GetString("wzrost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz Profil.
        /// </summary>
        public static string ZapiszProfil {
            get {
                return ResourceManager.GetString("ZapiszProfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz Ustawienia Diety.
        /// </summary>
        public static string zapiszUstawieniaDiety {
            get {
                return ResourceManager.GetString("zapiszUstawieniaDiety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz Ustawienia Powiadomień.
        /// </summary>
        public static string zapiszUstawieniaPowiadomien {
            get {
                return ResourceManager.GetString("zapiszUstawieniaPowiadomien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz Ustawienia Treningu.
        /// </summary>
        public static string zapiszUstawieniaTreningu {
            get {
                return ResourceManager.GetString("zapiszUstawieniaTreningu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdjęcie profilowe:.
        /// </summary>
        public static string ZdjęcieProfilowe {
            get {
                return ResourceManager.GetString("ZdjęcieProfilowe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień Zdjęcie:.
        /// </summary>
        public static string ZmienZdjęcie {
            get {
                return ResourceManager.GetString("ZmienZdjęcie", resourceCulture);
            }
        }
    }
}
