// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NOTlazyZone.Models.Context;

#nullable disable

namespace NOTlazyZone.Migrations
{
    [DbContext(typeof(NOTlazyZoneEntities))]
    [Migration("20231122192818_update")]
    partial class update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NOTlazyZone.Models.Entities.Adre", b =>
                {
                    b.Property<int>("AdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ad_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdId"));

                    b.Property<int?>("AdAdtId")
                        .HasColumnType("int")
                        .HasColumnName("ad_adt_id");

                    b.Property<bool?>("AdAktywny")
                        .HasColumnType("bit")
                        .HasColumnName("ad_aktywny");

                    b.Property<int?>("AdAtId")
                        .HasColumnType("int")
                        .HasColumnName("ad_at_id");

                    b.Property<DateTime?>("AdKiedyDodal")
                        .HasColumnType("datetime")
                        .HasColumnName("ad_kiedy_dodal");

                    b.Property<DateTime?>("AdKiedyUsunal")
                        .HasColumnType("datetime")
                        .HasColumnName("ad_kiedy_usunal");

                    b.Property<DateTime?>("AdKiedyZmodyfikowal")
                        .HasColumnType("datetime")
                        .HasColumnName("ad_kiedy_zmodyfikowal");

                    b.Property<string>("AdKod")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ad_kod");

                    b.Property<string>("AdKtoDodal")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ad_kto_dodal");

                    b.Property<string>("AdKtoUsunal")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ad_kto_usunal");

                    b.Property<string>("AdKtoZmodyfikowal")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ad_kto_zmodyfikowal");

                    b.Property<string>("AdMiejscowosc")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("ad_miejscowosc");

                    b.Property<string>("AdNazwa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ad_nazwa");

                    b.Property<string>("AdNrDomu")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ad_nr_domu");

                    b.Property<string>("AdNrLokalu")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ad_nr_lokalu");

                    b.Property<string>("AdOpis")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ad_opis");

                    b.Property<string>("AdUlica")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("ad_ulica");

                    b.Property<int?>("AdUsId")
                        .HasColumnType("int")
                        .HasColumnName("ad_us_id");

                    b.Property<string>("AdUwagi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ad_uwagi");

                    b.HasKey("AdId")
                        .HasName("PK__Adres__CAA4A627F4C1FCD8");

                    b.HasIndex("AdAdtId");

                    b.HasIndex("AdUsId");

                    b.ToTable("Adres");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.AdresTyp", b =>
                {
                    b.Property<int>("AdtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("adt_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdtId"));

                    b.Property<bool?>("AdtAktywny")
                        .HasColumnType("bit")
                        .HasColumnName("adt_aktywny");

                    b.Property<DateTime?>("AdtKiedyDodal")
                        .HasColumnType("datetime")
                        .HasColumnName("adt_kiedy_dodal");

                    b.Property<DateTime?>("AdtKiedyUsunal")
                        .HasColumnType("datetime")
                        .HasColumnName("adt_kiedy_usunal");

                    b.Property<DateTime?>("AdtKiedyZmodyfikowal")
                        .HasColumnType("datetime")
                        .HasColumnName("adt_kiedy_zmodyfikowal");

                    b.Property<string>("AdtKtoDodal")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("adt_kto_dodal");

                    b.Property<string>("AdtKtoUsunal")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("adt_kto_usunal");

                    b.Property<string>("AdtKtoZmodyfikowal")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("adt_kto_zmodyfikowal");

                    b.Property<string>("AdtNazwa")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("adt_nazwa");

                    b.HasKey("AdtId")
                        .HasName("PK__Adres_ty__960EEA71EB04031F");

                    b.ToTable("Adres_typ");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.CwiczeniaTyp", b =>
                {
                    b.Property<int>("CwtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cwt_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CwtId"));

                    b.Property<string>("CwtNazwa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("cwt_nazwa");

                    b.HasKey("CwtId")
                        .HasName("PK__Cwiczeni__F647F12AF48F0513");

                    b.ToTable("Cwiczenia_typ");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.Cwiczenium", b =>
                {
                    b.Property<int>("CwId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cw_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CwId"));

                    b.Property<bool?>("CwCardio")
                        .HasColumnType("bit")
                        .HasColumnName("cw_cardio");

                    b.Property<decimal?>("CwCiezar")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("cw_ciezar");

                    b.Property<int?>("CwCwtId")
                        .HasColumnType("int")
                        .HasColumnName("cw_cwt_id");

                    b.Property<string>("CwNazwa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("cw_nazwa");

                    b.Property<int?>("CwPowtorzenie")
                        .HasColumnType("int")
                        .HasColumnName("cw_powtorzenie");

                    b.Property<decimal?>("CwPrzerwa")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("cw_przerwa");

                    b.Property<int?>("CwSeria")
                        .HasColumnType("int")
                        .HasColumnName("cw_seria");

                    b.Property<int?>("CwTrudnosc")
                        .HasColumnType("int")
                        .HasColumnName("cw_trudnosc");

                    b.Property<int?>("CwUsId")
                        .HasColumnType("int")
                        .HasColumnName("cw_us_id");

                    b.HasKey("CwId")
                        .HasName("PK__Cwiczeni__BDC9D0EDE1CADCC5");

                    b.HasIndex("CwCwtId");

                    b.HasIndex("CwUsId");

                    b.ToTable("Cwiczenia");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.DietaTyp", b =>
                {
                    b.Property<int>("DatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("dat_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DatId"));

                    b.Property<string>("DatRodzaj")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("dat_rodzaj");

                    b.Property<int?>("DatUsId")
                        .HasColumnType("int")
                        .HasColumnName("dat_us_id");

                    b.HasKey("DatId")
                        .HasName("PK__Dieta_ty__92B5382919140F01");

                    b.HasIndex("DatUsId");

                    b.ToTable("Dieta_typ");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.Dietum", b =>
                {
                    b.Property<int>("DaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("da_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DaId"));

                    b.Property<int?>("DaColorie")
                        .HasColumnType("int")
                        .HasColumnName("da_colorie");

                    b.Property<int?>("DaDatId")
                        .HasColumnType("int")
                        .HasColumnName("da_dat_id");

                    b.Property<int?>("DaIloscBialka")
                        .HasColumnType("int")
                        .HasColumnName("da_ilosc_bialka");

                    b.Property<int?>("DaIloscTluszczy")
                        .HasColumnType("int")
                        .HasColumnName("da_ilosc_tluszczy");

                    b.Property<int?>("DaIloscWeglowodanow")
                        .HasColumnType("int")
                        .HasColumnName("da_ilosc_weglowodanow");

                    b.Property<string>("DaNazwa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("da_nazwa");

                    b.Property<int?>("DaUsId")
                        .HasColumnType("int")
                        .HasColumnName("da_us_id");

                    b.HasKey("DaId")
                        .HasName("PK__Dieta__BF7A3295703554FA");

                    b.HasIndex("DaDatId");

                    b.HasIndex("DaUsId");

                    b.ToTable("Dieta");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.Kontakty", b =>
                {
                    b.Property<int>("KoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ko_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KoId"));

                    b.Property<int?>("KoUsId")
                        .HasColumnType("int")
                        .HasColumnName("ko_us_id");

                    b.HasKey("KoId")
                        .HasName("PK__Kontakty__21DD6918B8D87463");

                    b.HasIndex("KoUsId");

                    b.ToTable("Kontakty");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.Mail", b =>
                {
                    b.Property<int>("MaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaId"));

                    b.Property<bool?>("MaAktywny")
                        .HasColumnType("bit")
                        .HasColumnName("ma_aktywny");

                    b.Property<DateTime?>("MaKiedyDodal")
                        .HasColumnType("datetime")
                        .HasColumnName("ma_kiedy_dodal");

                    b.Property<DateTime?>("MaKiedyUsunal")
                        .HasColumnType("datetime")
                        .HasColumnName("ma_kiedy_usunal");

                    b.Property<DateTime?>("MaKiedyZmodyfikowal")
                        .HasColumnType("datetime")
                        .HasColumnName("ma_kiedy_zmodyfikowal");

                    b.Property<string>("MaKtoDodal")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_kto_dodal");

                    b.Property<string>("MaKtoUsunal")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_kto_usunal");

                    b.Property<string>("MaKtoZmodyfikowal")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_kto_zmodyfikowal");

                    b.Property<string>("MaNazwa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_nazwa");

                    b.Property<string>("MaOpis")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ma_opis");

                    b.Property<int?>("MaUsId")
                        .HasColumnType("int")
                        .HasColumnName("ma_us_id");

                    b.Property<string>("MaUwagi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ma_uwagi");

                    b.HasKey("MaId")
                        .HasName("PK__Mail__0FE166A71A240F6E");

                    b.HasIndex("MaUsId");

                    b.ToTable("Mail");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.PlanTreningowy", b =>
                {
                    b.Property<int>("PtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pt_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PtId"));

                    b.Property<int?>("PtCwId")
                        .HasColumnType("int")
                        .HasColumnName("pt_cw_id");

                    b.Property<TimeSpan?>("PtCzas")
                        .HasColumnType("time")
                        .HasColumnName("pt_czas");

                    b.Property<int?>("PtTrudnosc")
                        .HasColumnType("int")
                        .HasColumnName("pt_trudnosc");

                    b.Property<int?>("PtUsId")
                        .HasColumnType("int")
                        .HasColumnName("pt_us_id");

                    b.HasKey("PtId")
                        .HasName("PK__PlanTren__5630B120E1102AA8");

                    b.HasIndex("PtCwId");

                    b.HasIndex("PtUsId");

                    b.ToTable("PlanTreningowy");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.Powiadomienium", b =>
                {
                    b.Property<int>("PoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("po_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PoId"));

                    b.Property<string>("PoNazwa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("po_nazwa");

                    b.Property<DateTime?>("PoTimestamp")
                        .HasColumnType("datetime")
                        .HasColumnName("po_timestamp");

                    b.Property<int?>("PoUsId")
                        .HasColumnType("int")
                        .HasColumnName("po_us_id");

                    b.HasKey("PoId")
                        .HasName("PK__Powiadom__368DA7F087DD48F9");

                    b.HasIndex("PoUsId");

                    b.ToTable("Powiadomienia");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.Produkty", b =>
                {
                    b.Property<int>("PrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pr_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrId"));

                    b.Property<decimal?>("PrCena")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("pr_cena");

                    b.Property<string>("PrNazwa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("pr_nazwa");

                    b.HasKey("PrId")
                        .HasName("PK__Produkty__47B09F8E57558DFD");

                    b.ToTable("Produkty");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.RolaUzytkownika", b =>
                {
                    b.Property<int>("RoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ro_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoId"));

                    b.Property<string>("RoRoleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ro_RoleName");

                    b.Property<int?>("RoUsId")
                        .HasColumnType("int")
                        .HasColumnName("ro_us_id");

                    b.HasKey("RoId")
                        .HasName("PK__RolaUzyt__55B52BD93F17149D");

                    b.HasIndex("RoUsId");

                    b.ToTable("RolaUzytkownika");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.StatystykiSilowni", b =>
                {
                    b.Property<int>("StId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("st_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StId"));

                    b.Property<int?>("StAdId")
                        .HasColumnType("int")
                        .HasColumnName("st_ad_id");

                    b.Property<int?>("StCwId")
                        .HasColumnType("int")
                        .HasColumnName("st_cw_id");

                    b.Property<DateTime?>("StDataZalozenia")
                        .HasColumnType("datetime")
                        .HasColumnName("st_data_zalozenia");

                    b.Property<bool?>("StDostepniTrenerzyPersonalni")
                        .HasColumnType("bit")
                        .HasColumnName("st_dostepni_trenerzy_personalni");

                    b.Property<string>("StGodzinyOtwarcia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("st_godziny_otwarcia");

                    b.Property<int?>("StLiczbaCzlonkow")
                        .HasColumnType("int")
                        .HasColumnName("st_liczba_czlonkow");

                    b.Property<int?>("StLiczbaKlientow")
                        .HasColumnType("int")
                        .HasColumnName("st_liczba_klientow");

                    b.Property<int?>("StMaId")
                        .HasColumnType("int")
                        .HasColumnName("st_ma_id");

                    b.Property<string>("StNajpopularniejszeZajecia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("st_najpopularniejsze_zajecia");

                    b.Property<string>("StNazwaSilowni")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("st_nazwa_silowni");

                    b.Property<double?>("StProcentowyWzrostLiczbyKlientow")
                        .HasColumnType("float")
                        .HasColumnName("st_procentowy_wzrost_liczby_klientow");

                    b.Property<int?>("StSredniaLiczbaOdwiedzinTygodniowo")
                        .HasColumnType("int")
                        .HasColumnName("st_srednia_liczba_odwiedzin_tygodniowo");

                    b.Property<string>("StStronaInterentowa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("st_strona_interentowa");

                    b.Property<int?>("StTnId")
                        .HasColumnType("int")
                        .HasColumnName("st_tn_id");

                    b.Property<int?>("StUsId")
                        .HasColumnType("int")
                        .HasColumnName("st_us_id");

                    b.Property<string>("StWlasciciel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("st_wlasciciel");

                    b.HasKey("StId")
                        .HasName("PK__Statysty__A85E81CF574246AE");

                    b.HasIndex("StAdId");

                    b.HasIndex("StCwId");

                    b.HasIndex("StMaId");

                    b.HasIndex("StTnId");

                    b.HasIndex("StUsId");

                    b.ToTable("Statystyki_silowni");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.Telefon", b =>
                {
                    b.Property<int>("TnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tn_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TnId"));

                    b.Property<bool?>("AdAktywny")
                        .HasColumnType("bit")
                        .HasColumnName("ad_aktywny");

                    b.Property<DateTime?>("AdKiedyDodal")
                        .HasColumnType("datetime")
                        .HasColumnName("ad_kiedy_dodal");

                    b.Property<DateTime?>("AdKiedyUsunal")
                        .HasColumnType("datetime")
                        .HasColumnName("ad_kiedy_usunal");

                    b.Property<DateTime?>("AdKiedyZmodyfikowal")
                        .HasColumnType("datetime")
                        .HasColumnName("ad_kiedy_zmodyfikowal");

                    b.Property<string>("AdKtoDodal")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ad_kto_dodal");

                    b.Property<string>("AdKtoUsunal")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ad_kto_usunal");

                    b.Property<string>("AdKtoZmodyfikowal")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ad_kto_zmodyfikowal");

                    b.Property<string>("AdOpis")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ad_opis");

                    b.Property<string>("AdUwagi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ad_uwagi");

                    b.Property<string>("TnNumer")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tn_numer");

                    b.Property<int?>("TnUsId")
                        .HasColumnType("int")
                        .HasColumnName("tn_us_id");

                    b.HasKey("TnId")
                        .HasName("PK__Telefon__15DDCE4A8A2518F6");

                    b.HasIndex("TnUsId");

                    b.ToTable("Telefon");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.Uzytkownicy", b =>
                {
                    b.Property<int>("UsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("us_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsId"));

                    b.Property<bool?>("UsAktywny")
                        .HasColumnType("bit")
                        .HasColumnName("us_aktywny");

                    b.Property<DateTime?>("UsDataRozpoczeciaOd")
                        .HasColumnType("datetime")
                        .HasColumnName("us_data_rozpoczecia_od");

                    b.Property<DateTime?>("UsDataZakonczeniaDo")
                        .HasColumnType("datetime")
                        .HasColumnName("us_data_zakonczenia_do");

                    b.Property<string>("UsImie")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("us_imie");

                    b.Property<DateTime?>("UsKiedyDodal")
                        .HasColumnType("datetime")
                        .HasColumnName("us_kiedy_dodal");

                    b.Property<DateTime?>("UsKiedyUsunal")
                        .HasColumnType("datetime")
                        .HasColumnName("us_kiedy_usunal");

                    b.Property<DateTime?>("UsKiedyZmodyfikowal")
                        .HasColumnType("datetime")
                        .HasColumnName("us_kiedy_zmodyfikowal");

                    b.Property<string>("UsKtoDodal")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("us_kto_dodal");

                    b.Property<string>("UsKtoUsunal")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("us_kto_usunal");

                    b.Property<string>("UsKtoZmodyfikowal")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("us_kto_zmodyfikowal");

                    b.Property<string>("UsNazwisko")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("us_nazwisko");

                    b.Property<string>("UsOpis")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("us_opis");

                    b.Property<string>("UsPesel")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("us_pesel");

                    b.Property<string>("UsUwagi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("us_uwagi");

                    b.HasKey("UsId")
                        .HasName("PK__Uzytkown__2E701A67DAD1BDA5");

                    b.ToTable("Uzytkownicy");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.Wiadomosci", b =>
                {
                    b.Property<int>("WiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("wi_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WiId"));

                    b.Property<DateTime?>("WiDataOtrzymania")
                        .HasColumnType("datetime")
                        .HasColumnName("wi_data_otrzymania");

                    b.Property<string>("WiZawartosc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("wi_zawartosc");

                    b.HasKey("WiId")
                        .HasName("PK__Wiadomos__0911F8635FE6D31F");

                    b.ToTable("Wiadomosci");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.Zamowienium", b =>
                {
                    b.Property<int>("ZaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("za_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZaId"));

                    b.Property<DateTime?>("ZaDataZamowienia")
                        .HasColumnType("datetime")
                        .HasColumnName("za_data_zamowienia");

                    b.Property<int?>("ZaIlosc")
                        .HasColumnType("int")
                        .HasColumnName("za_ilosc");

                    b.Property<int?>("ZaPrId")
                        .HasColumnType("int")
                        .HasColumnName("za_pr_id");

                    b.Property<int?>("ZaUsId")
                        .HasColumnType("int")
                        .HasColumnName("za_us_id");

                    b.HasKey("ZaId")
                        .HasName("PK__Zamowien__3F240B44E6894367");

                    b.HasIndex("ZaPrId");

                    b.HasIndex("ZaUsId");

                    b.ToTable("Zamowienia");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.Adre", b =>
                {
                    b.HasOne("NOTlazyZone.Models.Entities.AdresTyp", "AdAdt")
                        .WithMany("Adres")
                        .HasForeignKey("AdAdtId")
                        .HasConstraintName("FK__Adres__ad_adt_id__2C3393D0");

                    b.HasOne("NOTlazyZone.Models.Entities.Uzytkownicy", "AdUs")
                        .WithMany("Adres")
                        .HasForeignKey("AdUsId")
                        .HasConstraintName("FK__Adres__ad_us_id__2B3F6F97");

                    b.Navigation("AdAdt");

                    b.Navigation("AdUs");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.Cwiczenium", b =>
                {
                    b.HasOne("NOTlazyZone.Models.Entities.CwiczeniaTyp", "CwCwt")
                        .WithMany("Cwiczenia")
                        .HasForeignKey("CwCwtId")
                        .HasConstraintName("FK__Cwiczenia__cw_cw__31EC6D26");

                    b.HasOne("NOTlazyZone.Models.Entities.Uzytkownicy", "CwUs")
                        .WithMany("Cwiczenia")
                        .HasForeignKey("CwUsId")
                        .HasConstraintName("FK__Cwiczenia__cw_us__30F848ED");

                    b.Navigation("CwCwt");

                    b.Navigation("CwUs");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.DietaTyp", b =>
                {
                    b.HasOne("NOTlazyZone.Models.Entities.Uzytkownicy", "DatUs")
                        .WithMany("DietaTyps")
                        .HasForeignKey("DatUsId")
                        .HasConstraintName("FK__Dieta_typ__dat_u__3E52440B");

                    b.Navigation("DatUs");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.Dietum", b =>
                {
                    b.HasOne("NOTlazyZone.Models.Entities.DietaTyp", "DaDat")
                        .WithMany("Dieta")
                        .HasForeignKey("DaDatId")
                        .HasConstraintName("FK__Dieta__da_dat_id__4222D4EF");

                    b.HasOne("NOTlazyZone.Models.Entities.Uzytkownicy", "DaUs")
                        .WithMany("Dieta")
                        .HasForeignKey("DaUsId")
                        .HasConstraintName("FK__Dieta__da_us_id__412EB0B6");

                    b.Navigation("DaDat");

                    b.Navigation("DaUs");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.Kontakty", b =>
                {
                    b.HasOne("NOTlazyZone.Models.Entities.Uzytkownicy", "KoUs")
                        .WithMany("Kontakties")
                        .HasForeignKey("KoUsId")
                        .HasConstraintName("FK__Kontakty__ko_us___46E78A0C");

                    b.Navigation("KoUs");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.Mail", b =>
                {
                    b.HasOne("NOTlazyZone.Models.Entities.Uzytkownicy", "MaUs")
                        .WithMany("Mail")
                        .HasForeignKey("MaUsId")
                        .HasConstraintName("FK__Mail__ma_us_id__267ABA7A");

                    b.Navigation("MaUs");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.PlanTreningowy", b =>
                {
                    b.HasOne("NOTlazyZone.Models.Entities.Cwiczenium", "PtCw")
                        .WithMany("PlanTreningowies")
                        .HasForeignKey("PtCwId")
                        .HasConstraintName("FK__PlanTreni__pt_cw__5070F446");

                    b.HasOne("NOTlazyZone.Models.Entities.Uzytkownicy", "PtUs")
                        .WithMany("PlanTreningowies")
                        .HasForeignKey("PtUsId")
                        .HasConstraintName("FK__PlanTreni__pt_us__4F7CD00D");

                    b.Navigation("PtCw");

                    b.Navigation("PtUs");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.Powiadomienium", b =>
                {
                    b.HasOne("NOTlazyZone.Models.Entities.Uzytkownicy", "PoUs")
                        .WithMany("Powiadomienia")
                        .HasForeignKey("PoUsId")
                        .HasConstraintName("FK__Powiadomi__po_us__534D60F1");

                    b.Navigation("PoUs");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.RolaUzytkownika", b =>
                {
                    b.HasOne("NOTlazyZone.Models.Entities.Uzytkownicy", "RoUs")
                        .WithMany("RolaUzytkownikas")
                        .HasForeignKey("RoUsId")
                        .HasConstraintName("FK__RolaUzytk__ro_us__5629CD9C");

                    b.Navigation("RoUs");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.StatystykiSilowni", b =>
                {
                    b.HasOne("NOTlazyZone.Models.Entities.Adre", "StAd")
                        .WithMany("StatystykiSilownis")
                        .HasForeignKey("StAdId")
                        .HasConstraintName("FK__Statystyk__st_ad__38996AB5");

                    b.HasOne("NOTlazyZone.Models.Entities.Cwiczenium", "StCw")
                        .WithMany("StatystykiSilownis")
                        .HasForeignKey("StCwId")
                        .HasConstraintName("FK__Statystyk__st_cw__3B75D760");

                    b.HasOne("NOTlazyZone.Models.Entities.Mail", "StMa")
                        .WithMany("StatystykiSilownis")
                        .HasForeignKey("StMaId")
                        .HasConstraintName("FK__Statystyk__st_ma__3A81B327");

                    b.HasOne("NOTlazyZone.Models.Entities.Telefon", "StTn")
                        .WithMany("StatystykiSilownis")
                        .HasForeignKey("StTnId")
                        .HasConstraintName("FK__Statystyk__st_tn__398D8EEE");

                    b.HasOne("NOTlazyZone.Models.Entities.Uzytkownicy", "StUs")
                        .WithMany("StatystykiSilownis")
                        .HasForeignKey("StUsId")
                        .HasConstraintName("FK__Statystyk__st_us__37A5467C");

                    b.Navigation("StAd");

                    b.Navigation("StCw");

                    b.Navigation("StMa");

                    b.Navigation("StTn");

                    b.Navigation("StUs");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.Telefon", b =>
                {
                    b.HasOne("NOTlazyZone.Models.Entities.Uzytkownicy", "TnUs")
                        .WithMany("Telefons")
                        .HasForeignKey("TnUsId")
                        .HasConstraintName("FK__Telefon__tn_us_i__34C8D9D1");

                    b.Navigation("TnUs");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.Zamowienium", b =>
                {
                    b.HasOne("NOTlazyZone.Models.Entities.Produkty", "ZaPr")
                        .WithMany("Zamowienia")
                        .HasForeignKey("ZaPrId")
                        .HasConstraintName("FK__Zamowieni__za_pr__4CA06362");

                    b.HasOne("NOTlazyZone.Models.Entities.Uzytkownicy", "ZaUs")
                        .WithMany("Zamowienia")
                        .HasForeignKey("ZaUsId")
                        .HasConstraintName("FK__Zamowieni__za_us__4BAC3F29");

                    b.Navigation("ZaPr");

                    b.Navigation("ZaUs");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.Adre", b =>
                {
                    b.Navigation("StatystykiSilownis");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.AdresTyp", b =>
                {
                    b.Navigation("Adres");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.CwiczeniaTyp", b =>
                {
                    b.Navigation("Cwiczenia");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.Cwiczenium", b =>
                {
                    b.Navigation("PlanTreningowies");

                    b.Navigation("StatystykiSilownis");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.DietaTyp", b =>
                {
                    b.Navigation("Dieta");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.Mail", b =>
                {
                    b.Navigation("StatystykiSilownis");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.Produkty", b =>
                {
                    b.Navigation("Zamowienia");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.Telefon", b =>
                {
                    b.Navigation("StatystykiSilownis");
                });

            modelBuilder.Entity("NOTlazyZone.Models.Entities.Uzytkownicy", b =>
                {
                    b.Navigation("Adres");

                    b.Navigation("Cwiczenia");

                    b.Navigation("Dieta");

                    b.Navigation("DietaTyps");

                    b.Navigation("Kontakties");

                    b.Navigation("Mail");

                    b.Navigation("PlanTreningowies");

                    b.Navigation("Powiadomienia");

                    b.Navigation("RolaUzytkownikas");

                    b.Navigation("StatystykiSilownis");

                    b.Navigation("Telefons");

                    b.Navigation("Zamowienia");
                });
#pragma warning restore 612, 618
        }
    }
}
